<?php
$this -> title = 'Editar contanto';
$this -> headTitle($this -> title, 'PREPEND');
?>

<div class="row">
	<div class="col-lg-6 col-md-6 col-sm-6">
		<h3>Editar contacto</h3>
	</div>
	
	<div class="col-lg-6 col-md-6 col-sm-6">
		<h3 class="text-right">
			<a class="btn btn-success" href="<?php echo $this->baseUrl() . "/"; ?>">Regresar</a>
		</h3>
	</div>
</div>
<hr />
<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12">
		 <?php echo $this->form ?>
	</div>
</div>

