<?php
$this -> title = 'Agregar contanto';
$this -> headTitle($this -> title, 'PREPEND');
?>
<!-- TÍTULO -->
<div class="row">
	<div class="col-lg-6 col-md-6 col-sm-6">
		<h3>Listado de contactos</h3>
	</div>
	
	<div class="col-lg-6 col-md-6 col-sm-6">
		<h3 class="text-right">
			<a class="btn btn-success" data-toggle="modal" data-target="#add" href="javascript:;">Añadir contacto</a>
		</h3>
	</div>
</div>

<hr />

<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12">
		<table class="table table-condensed" id="example" width="100%">
			<thead>
				<tr>
					<th class="text-center">Nombre</th>
					<th class="text-center">Correo</th>
					<th class="text-center">Detalle</th>
					<th class="text-center">Editar</th>
				</tr>
			</thead>

			<tbody>
				<?php foreach ($this->contacto as $value) : ?>
				<tr>
					<td class="text-center"><?php echo trim($value['nombre'] .' '. $value['apellidoPaterno'] .' '. $value['apellidoMaterno'])?></td>
					<td class="text-center"><?php echo $value['correo'] ?></td>
					<td class="text-center">
						<a class="btn btn-default btn-xs" href="<?php echo $this->url(array('controller' => 'index', 'action' => 'detalle', 'id' => $value['id'])) ?>">Ver detalle</a>
					</td>
					<td class="text-center">
						<a class="btn btn-default btn-xs" href="<?php echo $this->url(array('controller' => 'index', 'action' => 'editar', 'id' => $value['id'])) ?>">Editar</a>
					</td>
				</tr>
				<?php endforeach; ?>
			</tbody>

		</table>
	</div>
</div>

<div class="modal fade" id="add">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Agregar contacto</h4>
            </div>
            <div class="modal-body">
               <?php echo $this->form ?>
            </div>
            
            <div id="msg"></div>
        </div>
    </div>
</div>