<?php echo $this->doctype(); ?>
<html lang="es">
    <head>
         <?php
        echo $this->headMeta();
        echo $this->headTitle();

        $this->headScript()
				->prependFile($this->baseUrl('/js/local.js'))
                ->prependFile($this->baseUrl('/js/bootstrap.min.js'))
				->prependFile($this->baseUrl('/jQueryUI/js/jquery.dataTables.js'))
				->prependFile($this->baseUrl('/js/jquery-1.8.3.min.js'));

        $this->headLink()
                ->prependStylesheet($this->baseUrl('/css/bootstrap.css'))
			    ->prependStylesheet($this->baseUrl('/jQueryUI/css/jquery.dataTables.css'));
			

        echo $this->headLink();
        echo $this->headScript();
        ?>
        
        <style>
        	html,
			body {
			  height: 100%;
			  background-color: #fff;
			}
			body {
			  color: #000;
			}
        </style>
    </head>
    <body>
        <div class="container">
            <?php echo $this->layout()->content;  ?>
        </div>
    </body>
</html>